### ISSUE TITLE
big sur layout lost

### ISSUE THREAD

**Issue by Andy-linux** [dwarvesf/hidden#88]
hidden can't save the layout on Big Sur, every time you restart, the last hidden icon layout will lost.

**Comment by p-z-l** [comment]
Any screenshots?

**Comment by phucledien** [comment]
hi @Andy-linux, thank you for raising the issue. 

I believe this is solved in #84 . I will release the new version soon 👍

**Comment by zhouk** [comment]
@phucledien Any ETA for releasing the fix for big sur?

**Comment by rami3l** [comment]
@phucledien Just being curious (and not pushy): is there anything that blocks the new release? :)

**Comment by viettrungphan** [comment]
We are testing it, the bug still appeared, Big Sur change the way system managed status bar icons somehow.

**Comment by marnovo** [comment]
I believe it might not be hidden's fault (or at least alone).
Over the Big Sur betas I have (among others) experienced menu bar icon positions reset every restart, and this behavior seems to persist despite hidden being loaded or not.

**Comment by marnovo** [comment]
More detailed info about the issue: https://github.com/feedback-assistant/reports/issues/151

**Comment by marnovo** [comment]
> **Apple Feedback**
> There are changes in the latest update, build 20C5048k, that may have resolved this issue.
You can see the software build your device is running and check for the latest update by clicking on the Apple logo in the upper left hand corner > About This Mac. If the build is not visible, click on the macOS version, e.g. 10.15.x, to reveal it.

Fixed on macOS 11.1 beta 1 (20C5048k) and continues fixed on beta 2 (20C5061b).

**Comment by fatihturan** [comment]
The bug still persist on macOS Big Sur 11.0.1.

**Comment by fatihturan** [comment]
This problem was fixed on macOS Big Sur. 11.1. 🎊

**Comment by yaohwu** [comment]
🎉

**Comment by viettrungphan** [comment]
Thanks all.
